### ISSUE TITLE
su -c option

### ISSUE THREAD

**Issue by jcalabres** [NotSoSecure/android_application_analyzer#2]
I have an error related too "su invalid -c", as some emulators are not using a su binary with "-c" option, an adaptation is needed.

**Comment by jcalabres** [comment]
Solved, waiting for commit confirmation.

**Comment by devsecboy** [comment]
As per the original code, it will check for su, if the application doesn't have that then it will start running the command with normal adb command-line utility.

However, I added the su checks due to the following issues raised 
"https://github.com/NotSoSecure/android_application_analyzer/issues/1"

For this particular test case, your suggested changes fail.

**Comment by devsecboy** [comment]
<img width="1010" alt="Screen Shot 2020-03-08 at 1 08 45 AM" src="https://user-images.githubusercontent.com/28931310/76152497-90b25f00-60d9-11ea-9d58-42c97b79d767.png">

Error message for the reference

**Comment by jcalabres** [comment]
Ok, you are correct. However, this implementation does not work on non-production builds. Tested by me the other day.
